"""initial_schema

Revision ID: a05bf0094fca
Revises: 
Create Date: 2026-04-24 19:12:09.568534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05bf0094fca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('asset_class', sa.Enum('stock', 'crypto', 'fund', 'etf', name='asset_class_enum', schema='abacus'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='abacus'
    )
    op.create_index(op.f('ix_abacus_assets_user_id'), 'assets', ['user_id'], unique=False, schema='abacus')
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('buy', 'sell', name='transaction_type_enum', schema='abacus'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.Column('broker', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['abacus.assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='abacus'
    )
    op.create_index(op.f('ix_abacus_transactions_user_id'), 'transactions', ['user_id'], unique=False, schema='abacus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abacus_transactions_user_id'), table_name='transactions', schema='abacus')
    op.drop_table('transactions', schema='abacus')
    op.drop_index(op.f('ix_abacus_assets_user_id'), table_name='assets', schema='abacus')
    op.drop_table('assets', schema='abacus')
    # ### end Alembic commands ###
